sqlserver:
  image: microsoft/mssql-server-linux
  hostname: sql_2
  environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Teste123
  ports:
    - 1433:1433

mongo-container:
  image: mongo
  environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=teste123
  ports:
    - "27017:27017"
  command: mongod